# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.5.9
  - 5.6
  - hhvm
  - 7.0

services:
  - mysql

# Commands to be run before your environment runs.
before_script:
  - cp .env.travis .env
  - mysql -e 'create database laravel_blog_home;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan migrate
  - php artisan db:seed
  - php artisan key:generate

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.5.9
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always